name: distribuidora_app_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons para iOS
  cupertino_icons: ^1.0.8

  # HTTP para consumir tu API
  http: ^1.1.0

  # Guardar token o datos de sesiÃ³n localmente
  shared_preferences: ^2.1.0

  # Formato de fechas y nÃºmeros
  intl: ^0.20.2

  # LocalizaciÃ³n de Material widgets
  flutter_localizations:
    sdk: flutter

  # ğŸ“Š LibrerÃ­a para grÃ¡ficos
  fl_chart: ^0.69.0

    # ğŸ§¾ Generar e imprimir PDFs
  pdf: ^3.11.1
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Fonts (ejemplo)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
